server.port=${PORT:8080}

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

logging.level.com.zaxxer.hikari=DEBUG
logging.level.org.postgresql=DEBUG

discord.bot.token=${DISCORD_TOKEN}
discord.public.key=${DISCORD_PUBLIC_KEY}
discord.mirror.channel.id=${DISCORD_MIRROR_CHANNEL_ID}
spring.security.user.name=${ADMIN_USERNAME}
spring.security.user.password=${ADMIN_PASSWORD}
discord.mirror.webhook-url=${DISCORD_MIRROR_WEBHOOK_URL}